# Fish completion for sonar-cli
# Generated by SonarQube CLI

# Main commands
set -l sonar_commands init scan setup status version auth config projects properties completion

# Auth subcommands
set -l auth_commands login logout status whoami

# Config subcommands  
set -l config_commands show set get reset

# Projects subcommands
set -l projects_commands list show create delete search

# Properties subcommands
set -l properties_commands generate templates template validate

# Completion subcommands
set -l completion_commands install uninstall show

# Languages for properties
set -l languages javascript typescript java python csharp cpp go php kotlin swift ruby scala html css xml yaml json dockerfile terraform multi

# Completion functions
function __fish_sonar_no_subcommand
    not __fish_seen_subcommand_from $sonar_commands
end

function __fish_sonar_using_subcommand
    set cmd (commandline -opc)
    if [ (count $cmd) -gt 1 ]
        if contains -- $cmd[2] $argv
            return 0
        end
    end
    return 1
end

# Main commands completion
complete -f -c sonar-cli -n '__fish_sonar_no_subcommand' -a 'init' -d 'Interactive setup for new projects'
complete -f -c sonar-cli -n '__fish_sonar_no_subcommand' -a 'scan' -d 'Quick scan current project'
complete -f -c sonar-cli -n '__fish_sonar_no_subcommand' -a 'setup' -d 'One-time CLI setup wizard'
complete -f -c sonar-cli -n '__fish_sonar_no_subcommand' -a 'status' -d 'Show configuration and connection status'
complete -f -c sonar-cli -n '__fish_sonar_no_subcommand' -a 'version' -d 'Show version information'
complete -f -c sonar-cli -n '__fish_sonar_no_subcommand' -a 'auth' -d 'Authentication management'
complete -f -c sonar-cli -n '__fish_sonar_no_subcommand' -a 'config' -d 'Configuration management'
complete -f -c sonar-cli -n '__fish_sonar_no_subcommand' -a 'projects' -d 'Project management'
complete -f -c sonar-cli -n '__fish_sonar_no_subcommand' -a 'properties' -d 'Generate sonar-project.properties files'
complete -f -c sonar-cli -n '__fish_sonar_no_subcommand' -a 'completion' -d 'Shell completion management'

# Auth subcommands
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand auth' -a 'login' -d 'Login to SonarQube'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand auth' -a 'logout' -d 'Logout and clear authentication'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand auth' -a 'status' -d 'Show authentication status'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand auth' -a 'whoami' -d 'Show current user information'

# Config subcommands
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand config' -a 'show' -d 'Show current configuration'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand config' -a 'set' -d 'Set configuration value'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand config' -a 'get' -d 'Get configuration value'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand config' -a 'reset' -d 'Reset configuration'

# Projects subcommands
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand projects' -a 'list' -d 'List projects'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand projects' -a 'show' -d 'Show project details'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand projects' -a 'create' -d 'Create new project'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand projects' -a 'delete' -d 'Delete project'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand projects' -a 'search' -d 'Search projects'

# Properties subcommands
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand properties' -a 'generate' -d 'Generate properties file'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand properties' -a 'templates' -d 'List available templates'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand properties' -a 'template' -d 'Show template details'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand properties' -a 'validate' -d 'Validate properties file'

# Completion subcommands
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand completion' -a 'install' -d 'Install shell completion'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand completion' -a 'uninstall' -d 'Uninstall shell completion'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand completion' -a 'show' -d 'Show completion script'

# Options for specific commands
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand auth login' -l token -s t -d 'Authentication token'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand auth login' -l username -s u -d 'Username'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand auth login' -l password -s p -d 'Password'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand auth login' -l host -s h -d 'SonarQube host URL'

complete -f -c sonar-cli -n '__fish_sonar_using_subcommand auth status' -l verbose -s v -d 'Show detailed information'

complete -f -c sonar-cli -n '__fish_sonar_using_subcommand properties generate' -l key -s k -d 'Project key'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand properties generate' -l name -s n -d 'Project name'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand properties generate' -l language -s l -d 'Primary language' -a "$languages"
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand properties generate' -l description -s d -d 'Project description'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand properties generate' -l version -s v -d 'Project version'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand properties generate' -l interactive -s i -d 'Interactive mode'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand properties generate' -l show -d 'Show content without writing file'

complete -f -c sonar-cli -n '__fish_sonar_using_subcommand properties template' -a "$languages" -d 'Language template'

complete -f -c sonar-cli -n '__fish_sonar_using_subcommand completion install' -l shell -s s -d 'Shell type' -a 'bash zsh fish'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand completion uninstall' -l shell -s s -d 'Shell type' -a 'bash zsh fish'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand completion show' -a 'bash zsh fish' -d 'Shell type'

complete -f -c sonar-cli -n '__fish_sonar_using_subcommand scan' -l properties -s p -d 'Properties file path'
complete -f -c sonar-cli -n '__fish_sonar_using_subcommand scan' -l dir -s d -d 'Project directory'

# Global options
complete -f -c sonar-cli -l verbose -s v -d 'Enable verbose logging'
complete -f -c sonar-cli -l config -s c -d 'Configuration file path'
complete -f -c sonar-cli -l host -s h -d 'SonarQube host URL'
complete -f -c sonar-cli -l token -s t -d 'Authentication token'
complete -f -c sonar-cli -l help -d 'Show help message'

# Copy all completions for 'sonar' command as well
complete -f -c sonar -n '__fish_sonar_no_subcommand' -a 'init' -d 'Interactive setup for new projects'
complete -f -c sonar -n '__fish_sonar_no_subcommand' -a 'scan' -d 'Quick scan current project'
complete -f -c sonar -n '__fish_sonar_no_subcommand' -a 'setup' -d 'One-time CLI setup wizard'
complete -f -c sonar -n '__fish_sonar_no_subcommand' -a 'status' -d 'Show configuration and connection status'
complete -f -c sonar -n '__fish_sonar_no_subcommand' -a 'version' -d 'Show version information'
complete -f -c sonar -n '__fish_sonar_no_subcommand' -a 'auth' -d 'Authentication management'
complete -f -c sonar -n '__fish_sonar_no_subcommand' -a 'config' -d 'Configuration management'
complete -f -c sonar -n '__fish_sonar_no_subcommand' -a 'projects' -d 'Project management'
complete -f -c sonar -n '__fish_sonar_no_subcommand' -a 'properties' -d 'Generate sonar-project.properties files'
complete -f -c sonar -n '__fish_sonar_no_subcommand' -a 'completion' -d 'Shell completion management'

complete -f -c sonar -n '__fish_sonar_using_subcommand auth' -a 'login' -d 'Login to SonarQube'
complete -f -c sonar -n '__fish_sonar_using_subcommand auth' -a 'logout' -d 'Logout and clear authentication'
complete -f -c sonar -n '__fish_sonar_using_subcommand auth' -a 'status' -d 'Show authentication status'
complete -f -c sonar -n '__fish_sonar_using_subcommand auth' -a 'whoami' -d 'Show current user information'

complete -f -c sonar -n '__fish_sonar_using_subcommand config' -a 'show' -d 'Show current configuration'
complete -f -c sonar -n '__fish_sonar_using_subcommand config' -a 'set' -d 'Set configuration value'
complete -f -c sonar -n '__fish_sonar_using_subcommand config' -a 'get' -d 'Get configuration value'
complete -f -c sonar -n '__fish_sonar_using_subcommand config' -a 'reset' -d 'Reset configuration'

complete -f -c sonar -n '__fish_sonar_using_subcommand projects' -a 'list' -d 'List projects'
complete -f -c sonar -n '__fish_sonar_using_subcommand projects' -a 'show' -d 'Show project details'
complete -f -c sonar -n '__fish_sonar_using_subcommand projects' -a 'create' -d 'Create new project'
complete -f -c sonar -n '__fish_sonar_using_subcommand projects' -a 'delete' -d 'Delete project'
complete -f -c sonar -n '__fish_sonar_using_subcommand projects' -a 'search' -d 'Search projects'

complete -f -c sonar -n '__fish_sonar_using_subcommand properties' -a 'generate' -d 'Generate properties file'
complete -f -c sonar -n '__fish_sonar_using_subcommand properties' -a 'templates' -d 'List available templates'
complete -f -c sonar -n '__fish_sonar_using_subcommand properties' -a 'template' -d 'Show template details'
complete -f -c sonar -n '__fish_sonar_using_subcommand properties' -a 'validate' -d 'Validate properties file'

complete -f -c sonar -n '__fish_sonar_using_subcommand completion' -a 'install' -d 'Install shell completion'
complete -f -c sonar -n '__fish_sonar_using_subcommand completion' -a 'uninstall' -d 'Uninstall shell completion'
complete -f -c sonar -n '__fish_sonar_using_subcommand completion' -a 'show' -d 'Show completion script'

complete -f -c sonar -n '__fish_sonar_using_subcommand auth login' -l token -s t -d 'Authentication token'
complete -f -c sonar -n '__fish_sonar_using_subcommand auth login' -l username -s u -d 'Username'
complete -f -c sonar -n '__fish_sonar_using_subcommand auth login' -l password -s p -d 'Password'
complete -f -c sonar -n '__fish_sonar_using_subcommand auth login' -l host -s h -d 'SonarQube host URL'

complete -f -c sonar -n '__fish_sonar_using_subcommand auth status' -l verbose -s v -d 'Show detailed information'

complete -f -c sonar -n '__fish_sonar_using_subcommand properties generate' -l key -s k -d 'Project key'
complete -f -c sonar -n '__fish_sonar_using_subcommand properties generate' -l name -s n -d 'Project name'
complete -f -c sonar -n '__fish_sonar_using_subcommand properties generate' -l language -s l -d 'Primary language' -a "$languages"
complete -f -c sonar -n '__fish_sonar_using_subcommand properties generate' -l description -s d -d 'Project description'
complete -f -c sonar -n '__fish_sonar_using_subcommand properties generate' -l version -s v -d 'Project version'
complete -f -c sonar -n '__fish_sonar_using_subcommand properties generate' -l interactive -s i -d 'Interactive mode'
complete -f -c sonar -n '__fish_sonar_using_subcommand properties generate' -l show -d 'Show content without writing file'

complete -f -c sonar -n '__fish_sonar_using_subcommand properties template' -a "$languages" -d 'Language template'

complete -f -c sonar -n '__fish_sonar_using_subcommand completion install' -l shell -s s -d 'Shell type' -a 'bash zsh fish'
complete -f -c sonar -n '__fish_sonar_using_subcommand completion uninstall' -l shell -s s -d 'Shell type' -a 'bash zsh fish'
complete -f -c sonar -n '__fish_sonar_using_subcommand completion show' -a 'bash zsh fish' -d 'Shell type'

complete -f -c sonar -n '__fish_sonar_using_subcommand scan' -l properties -s p -d 'Properties file path'
complete -f -c sonar -n '__fish_sonar_using_subcommand scan' -l dir -s d -d 'Project directory'

complete -f -c sonar -l verbose -s v -d 'Enable verbose logging'
complete -f -c sonar -l config -s c -d 'Configuration file path'
complete -f -c sonar -l host -s h -d 'SonarQube host URL'
complete -f -c sonar -l token -s t -d 'Authentication token'
complete -f -c sonar -l help -d 'Show help message'
